---
kind: pipeline
type: docker
name: buildsite
steps:
- name: build
  image: squidfunk/mkdocs-material
  pull: if-not-exists
  volumes:
  - name: site
    path: /site
  commands:
  - pip install -U -r ./requirements.txt
  - mkdocs build
  - cp -r site/ /site
  - chmod -R 777 /site
volumes:
- name: site
  host:
    path: /mnt/nvme2tb/appdata/foundation
image_pull_secrets:
- dockerconfig